# Generated by Django 6.0.4 on 2026-05-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
