[build]
builder = "RAILPACK"
buildCommand = "python backend/manage.py collectstatic --noinput"

[deploy]
preDeployCommand = "python backend/manage.py migrate"
startCommand = "gunicorn --chdir backend backend.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/health/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
